apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment-static
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/manifests
    repoURL: https://github.com/ruszkipista/cn04-helm-demo
    targetRevision: HEAD
  syncPolicy: {}