## The chart API version
apiVersion: v1
## The name of the chart
name: nginx-deployment
## A single-sentence description of this project
description: Install NGINX webserver with ArgoCD + Helm templates
## A list of keywords about this project to quickly identify the chart's capabilities.
keywords:
- nginx
## The chart version, here set to `3.7.0`
version: 1.0.0
## List of maintainers, their names, and method of contact
maintainers:
- name: ruszkipista
  email: ruszkipista@mail.com